[build]
  # Since this is a simple HTML site, there is no build command.
  command = ""
  
  # The directory to deploy. The root directory contains index.html
  publish = "."

# Make sure all traffic is served properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
